# Generated by Django 4.2.11 on 2026-03-02 14:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamadaGenerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camada Genérica',
                'verbose_name_plural': 'Camadas Genéricas',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CamadaEstadual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do estado ou município.', max_length=255)),
                ('uf', models.CharField(db_index=True, help_text='Sigla do estado (ex: SC).', max_length=2)),
                ('tipo', models.CharField(choices=[('ESTADO', 'Estado'), ('MUNICIPIO', 'Município')], default='ESTADO', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geometria do limite (SRID 4326).', srid=4326)),
                ('fonte', models.CharField(blank=True, default='', help_text='Fonte do dado (ex: IBGE 2023).', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Camada Estadual',
                'verbose_name_plural': 'Camadas Estaduais',
                'ordering': ['uf', 'nome'],
                'indexes': [models.Index(fields=['uf'], name='layers_cama_uf_1735dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CamadaAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('RESERVA_LEGAL', 'Reserva Legal'), ('APP', 'Área de Preservação Permanente'), ('UNIDADE_CONSERVACAO', 'Unidade de Conservação'), ('ASSENTAMENTO', 'Assentamento'), ('OUTRO', 'Outro')], db_index=True, max_length=30)),
                ('codigo', models.CharField(blank=True, default='', help_text='Código identificador externo (ex: CAR, SNUC).', max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('fonte', models.CharField(blank=True, default='', max_length=255)),
                ('uf', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camada Ambiental',
                'verbose_name_plural': 'Camadas Ambientais',
                'ordering': ['tipo', 'nome'],
                'indexes': [models.Index(fields=['tipo', 'uf'], name='layers_cama_tipo_1fc7cb_idx')],
            },
        ),
    ]
