# Generated by Django 4.2.11 on 2026-03-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_camadamunicipal_alter_camadaestadual'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='camadamunicipal',
            new_name='layers_cama_uf_08a494_idx',
            old_name='layers_mun_uf_idx',
        ),
        migrations.RenameIndex(
            model_name='camadamunicipal',
            new_name='layers_cama_codigo__b05cfe_idx',
            old_name='layers_mun_ibge_idx',
        ),
    ]
